### ISSUE TITLE
Roadmap/plan

### ISSUE THREAD

**Issue by VadimSaveljev** [SaltyCucumber/assets-portal#13]
Current task:
- [ ] add new button styles, streamline button design (https://github.com/SaltyCucumber/assets-portal/pull/64)

Todo:
- [ ] implement new mint NFT flow
- [ ] Create a persistent wallet loader for 5 seconds or so, to prevent empty connection form
- [ ] Ability to add SEO tags or prevent indexation where not needed
- [ ] add NFT ID field as optional, so that user may enter one if they so desire
- [ ] need to provide info to the user what each mint type means, cause it's otherwise unclear
- [ ] should not be able to submit metadata if nothing was changed
- [ ] add custom styles for date range picker according to current theme
- [ ] create a more robust solution to select default chain, in case the chain is faulty, a loop through chains should help
- [ ] image processing service integration, different sizes and caching of images
- [ ] implement https://reactjs.org/docs/error-boundaries.html

Done:
- [x] get rid of old theme styles, replace with new (https://github.com/SaltyCucumber/assets-portal/pull/63)
- [x] Validate user has enough funds to create a pool (https://github.com/SaltyCucumber/assets-portal/pull/62)
- [x] Sort tokens and pools alphabetically (https://github.com/SaltyCucumber/assets-portal/pull/61)
- [x] add rules for merging into main branch (https://github.com/SaltyCucumber/assets-portal/pull/58)
- [x] make header take the whole viewport + add name to logo (https://github.com/SaltyCucumber/assets-portal/pull/57)
- [x] add typescript linter (https://github.com/SaltyCucumber/assets-portal/pull/56)
- [x] lay groundwork for themes, icons, fonts according to design in figma (https://github.com/SaltyCucumber/assets-portal/pull/55)
- [x] Display token's supply instead of balance and rename Dex to AssetConversion (https://github.com/SaltyCucumber/assets-portal/pull/54)
- [x] upgrade private route handling with redirects and calls to action where appropriate (https://github.com/SaltyCucumber/assets-portal/pull/53)
- [x] mint NFT and its metadata in one batch transaction and setup ID automatically (https://github.com/SaltyCucumber/assets-portal/pull/51)
- [x] new routing according to the updated design (https://github.com/SaltyCucumber/assets-portal/pull/52)
- [x] on brave linux, drag and drop works but click to upload file doesn't (https://github.com/SaltyCucumber/assets-portal/pull/50)
- [x] pools page added (https://github.com/SaltyCucumber/assets-portal/pull/49)
- [x] add a dropdown to connect button functionality (https://github.com/SaltyCucumber/assets-portal/pull/48)
- [x] On chain change need to reset data or redirect to homepage (https://github.com/SaltyCucumber/assets-portal/pull/47)
- [x] update libs and set to precise versions (https://github.com/SaltyCucumber/assets-portal/pull/46)
- [x] redesign navigation menu (https://github.com/SaltyCucumber/assets-portal/pull/45)
- [x] Make private routes refreshable without redirects if logged in account is present (https://github.com/SaltyCucumber/assets-portal/pull/38)
- [x] awaiting nfts pallet change, must rename 'ownerOfItem' to 'ownedItem' (https://github.com/SaltyCucumber/assets-portal/pull/39)
- [x] awaiting PalletAttributes to arrive in @polkadot/api in order to use .isUsedToClaim() (https://github.com/SaltyCucumber/assets-portal/pull/39)
- [x] make main routes available without having to login immediately (https://github.com/SaltyCucumber/assets-portal/pull/37)
- [x] Tokens page (https://github.com/SaltyCucumber/assets-portal/pull/34)
- [x] Add advanced form fields to NFT minting; fix MintType HolderOf (https://github.com/SaltyCucumber/assets-portal/pull/33)
- [x] Create a separate page for collection minting (https://github.com/SaltyCucumber/assets-portal/pull/31)
- [x] Add advanced form fields to collection minting (https://github.com/SaltyCucumber/assets-portal/pull/31)
- [x] add a nicer image droparea (some lib) (https://github.com/SaltyCucumber/assets-portal/pull/30)
- [x] on collection/nft metadata submit do a redirect on success or show error if something went wrong (https://github.com/SaltyCucumber/assets-portal/pull/28)
- [x] add loader where necessary, especially when something async is happening in the background (https://github.com/SaltyCucumber/assets-portal/pull/28)
- [x] make design themeable, change default styles to correspond to Kusama network more instead of Polkadot (https://github.com/SaltyCucumber/assets-portal/pull/24, https://github.com/SaltyCucumber/assets-portal/pull/29)
- [x] add functionality to change current chain (https://github.com/SaltyCucumber/assets-portal/pull/18)
- [x] change import order automatically in yarn format; update readme; change Contexts folder name to contexts (https://github.com/SaltyCucumber/assets-portal/pull/17)
- [x] save current account to localstorage, so that there will be no need to manually select acc everytime a refresh is done
(https://github.com/SaltyCucumber/assets-portal/pull/16)
- [x] clean up design of the wallet connection part + dropdown design (https://github.com/SaltyCucumber/assets-portal/pull/15)
- [x]  add a proper image uploading process + previews of the said images (https://github.com/SaltyCucumber/assets-portal/pull/14)

**Comment by hamidra** [comment]
If you find bootstrap a bit opinionated take a look at [headlessui](https://headlessui.com/) it has a set of light weight basic components. It is designed to work well with tailwind, but you can explore how they works as basic components.

**Comment by VadimSaveljev** [comment]
Roadmap has moved to Projects tab, if you need access, let me know
